POST http://localhost:3003/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "id": "111222",
  "date": "2020-10-20",
  "specialist": "MD Jaime",
  "type": "HealthCheck",
  "description": "Yearly control visit. All clear.",
  "healthCheckRating": 0
}