POST http://localhost:3003/api/patients
Content-Type: application/json

{
  "name": "Joe Malone",
  "dateOfBirth": "2000-07-07",
  "ssn": "4444-5555",
  "gender": "other",
  "occupation": "perfumerist"
}